# Generated by Django 2.0.3 on 2018-04-12 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateSurvey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
    ]
