# Generated by Django 2.0.3 on 2018-04-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateSurvey', '0002_remove_question_question_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
