# Generated by Django 2.0.3 on 2018-04-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateSurvey', '0003_auto_20180412_0228'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('response', 'question')},
        ),
    ]
