# Generated by Django 2.0.3 on 2018-04-12 07:12

from django.db import migrations, models
import pgcrypto_expressions.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CreateSurvey', '0004_auto_20180412_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_field',
            field=pgcrypto_expressions.fields.EncryptedTextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='response',
            name='interview_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
