# Generated by Django 2.0.3 on 2018-04-24 17:16

from django.db import migrations
import pgcrypto_expressions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CreateSurvey', '0005_auto_20180412_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_field',
            field=pgcrypto_expressions.fields.EncryptedTextField(max_length=500),
        ),
    ]
