# Generated by Django 2.0.3 on 2018-04-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateSurvey', '0006_auto_20180424_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='encrypted',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='anonymous',
        ),
    ]
