# Generated by Django 2.0.3 on 2018-04-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateSurvey', '0007_auto_20180424_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
